version: "3"
services:
 db:
    image: mysql:5.6
    networks:
      - candy-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user 
    ports:
      - 3300:3306

networks:
  candy-mysql: 